name: Rust CI for Multiple Projects

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - database/rust-database-consumer
          - iot_device/rust-image-provider
          - ml_model/rust-inference-consumer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Navigate to project folder
        working-directory: ${{ matrix.project }}
        run: echo "Working directory set to ${{ matrix.project }}"

      - name: Check code formatting with rustfmt
        working-directory: ${{ matrix.project }}
        run: cargo fmt -- --check

      - name: Run Clippy to check for warnings and errors
        working-directory: ${{ matrix.project }}
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build the project
        working-directory: ${{ matrix.project }}
        run: cargo build --verbose

      - name: Run unit tests
        working-directory: ${{ matrix.project }}
        run: cargo test --verbose
