name: Rust CI for Multiple Projects

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Ensure dependencies exist
        run: sudo apt-get install libsqlite3-dev

      - name: Check code formatting with rustfmt
        run: cargo fmt -- --check

      - name: Run Clippy to check for warnings and errors
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build the project
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --verbose
